FLOOD_FIELDS = [
    "GDACS_ID",
    "equi7_grid_code",
    "country",
    "iso3",
    "eventid",
    "alertlevel",
    "alertscore",
    "fromdate",
    "todate",
    "geometry_url",
    "report_url",
    "details_url",
    "geometry",
]
